# Generated by Django 5.0 on 2023-12-16 05:55

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='User Phone Number', max_length=31),
        ),
    ]
